### ISSUE TITLE
AdaBoostClassifier not correctly converted to ONNX

### ISSUE THREAD

**Issue by ROC5COR** [onnx/sklearn-onnx#796]
Hello,
I trained an AdaBoostClassifier with sklearn, converted to ONNX using sk2onnx package (using float64 as dtype), it succeed creating the ONNX file, but then I am unable to import the file using onnxruntime. I am getting: 

`[ONNXRuntimeError]` : 10 : INVALID_GRAPH : Load model from adaboost_float32_opset.onnx failed:This i
s an invalid model. Error in Node:TreeEnsembleClassifier12 : Mismatched attribute type in 'TreeEnsembleClassifier
12 : class_weights'`

Here is the code to reproduce the problem: 
```python
print("AdaBoostClassifier")
clf = AdaBoostClassifier()
clf.fit(X, Y)
onx = to_onnx(clf, np.array(X).astype(np.float64), target_opset=15)
with open("adaboost_float64.onnx", "wb") as f:
    f.write(onx.SerializeToString())
sess = nxr.InferenceSession("adaboost_float64.onnx")
```

Then trying without the cast to **float64** but **float32** (what I am wanted originally) I am getting the error when exporting to onnx:
`RuntimeError: Parameter 'min' must be a string or a float.`

Here is the code to reproduce the second error:
```python
print("AdaBoostClassifier")
clf = AdaBoostClassifier()
clf.fit(X, Y)
onx = to_onnx(clf, np.array(X).astype(np.float32))
with open("adaboost_float32.onnx", "wb") as f:
    f.write(onx.SerializeToString())
```

Can you help me with this problem ? 
Thanks

**Comment by xadupre** [comment]
PR #795 should fix that bug. I'll make a new release soon.

**Comment by jacktwosense** [comment]
I'm still experiencing this error using float64 with v1.11:
`onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in 'TreeEnsembleClassifier : class_weights'`

**Comment by xadupre** [comment]
onnx has released a new version and changed the TreeEnsembleClassifier specifications. You need to change the following line:

``onx = to_onnx(clf, np.array(X).astype(np.float32), target_opset={'': 15, 'ai.onnx.ml': 2})``

**Comment by xiaowuhu** [comment]
@ROC5COR Hi, we will close this issue if you don't have any concern.
